// Generates mindovermatter/pages/icons.jsx: slimmed-down Phosphor icons containing only the styles the site uses.
//
// Each Phosphor icon ships all six styles (thin, light, regular, bold, fill, duotone), roughly 3.4 KB per icon,
// and every one ends up in the download. This script keeps just the duotone style (the site default) and,
// for brand logos (names ending in "Logo"), the solid "fill" style they are drawn with.
//
// Usage: add the icon name to the `from './icons.jsx'` import in pages/main.jsx, then run `npm run icons`.
// Icon names: https://phosphoricons.com
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

const siteRoot = join(import.meta.dirname, '..');
const mainFile = join(siteRoot, 'pages/main.jsx');
const outFile = join(siteRoot, 'pages/icons.jsx');
const defsDir = join(siteRoot, 'node_modules/@phosphor-icons/react/dist/defs');
const EXPORTS_KEPT_AS_IS = new Set(['IconContext']);

// 1. Which icons does the site import?
const importMatch = readFileSync(mainFile, 'utf8').match(/import\s*\{([^}]+)\}\s*from\s*'\.\/icons\.jsx'/);
if (!importMatch) throw new Error("Couldn't find `import { … } from './icons.jsx'` in pages/main.jsx");
const names = importMatch[1].split(',').map((name) => name.trim()).filter((name) => name && !EXPORTS_KEPT_AS_IS.has(name));

// 2. Load each icon's definitions with a stand-in React that records elements instead of rendering them.
const scratch = mkdtempSync(join(tmpdir(), 'phosphor-'));
const stubReact = join(scratch, 'react-stub.mjs');
writeFileSync(stubReact, `export const Fragment = 'Fragment';
export function createElement(type, props, ...children) { return { type, props: props ?? {}, children }; }`);

function toJsx(node) {
  if (typeof node === 'string') return node;
  const children = node.children.map(toJsx).join('');
  if (node.type === 'Fragment') return children;
  const attrs = Object.entries(node.props).map(([key, value]) => ` ${key}=${JSON.stringify(String(value))}`).join('');
  return children ? `<${node.type}${attrs}>${children}</${node.type}>` : `<${node.type}${attrs} />`;
}

const blocks = [];
try {
  for (const name of names) {
    const source = readFileSync(join(defsDir, `${name}.es.js`), 'utf8').replace(/from\s*"react"/, `from ${JSON.stringify(pathToFileURL(stubReact).href)}`);
    const tempFile = join(scratch, `${name}.mjs`);
    writeFileSync(tempFile, source);
    const module = await import(pathToFileURL(tempFile).href);
    const weights = Object.values(module).find((value) => value instanceof Map);
    const weight = name.endsWith('Logo') ? 'fill' : 'duotone';
    if (!weights?.has(weight)) throw new Error(`${name} has no "${weight}" style`);
    blocks.push(`export const ${name} = makeIcon('${name}', '${weight}', <>${toJsx(weights.get(weight))}</>);`);
  }
} finally {
  rmSync(scratch, { recursive: true, force: true });
}

// 3. Write the module.
writeFileSync(outFile, `// GENERATED by scripts/build-icons.mjs. Do not edit by hand.
// To add an icon, import it in pages/main.jsx from './icons.jsx', then run \`npm run icons\`.
// Phosphor Icons (MIT): only the styles the site uses are kept, to keep the download small.
import { forwardRef } from 'react';
import { IconBase, IconContext } from '@phosphor-icons/react';

export { IconContext };

// Each icon has one style; it is used whatever weight is requested, so nothing renders blank.
function makeIcon(name, weight, paths) {
  const weights = new Map([[weight, paths]]);
  const Icon = forwardRef((props, ref) => <IconBase ref={ref} {...props} weight={weight} weights={weights} />);
  Icon.displayName = name;
  return Icon;
}

${blocks.join('\n')}
`);

console.log(`Wrote ${names.length} icons to ${outFile}`);
